version: '3.9'

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
  php:
    build: 
      context: .
      dockerfile: dockerfiles/php.dockerfile
    ports:
      - 5173:5173
    volumes: 
      - ./src:/var/www/html:delegated
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: 
        - ./src:/var/www/html
  artisan:
    build: 
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm: 
    image: node:latest
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html